messages:
  coords:
    - '&cUsage: /f show <kothname>'

end-to-world:
  world: world
  x: 0
  y: 72
  z: 300
  yaw: 90
  pitch: 0

spawn:
  world: world
  x: 0
  y: 73
  z: 0
  yaw: -135
  pitch: 0

# The mysql login information
mysql:
  host: localhost
  user: root
  pass: idiot
  db: blacklist

# Report cooldown in seconds
report-cooldown: 120

# Helpop cooldown in seconds
helpop-cooldown: 10


